services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    command: npm run dev
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app


  # # Supabase ローカル実行（本番は Supabase Cloud を使う想定）
  # db:
  #   image: supabase/postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_PASSWORD: example